GET http://localhost:3000/
###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "100pour100inde@gmail.com",
    "password": "admin"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "100pour100inde@gmail.com",
    "password": "admin"
}
###

GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGYxOTQzYmIwZDk5MjRhYmM3YzRjMWIiLCJpYXQiOjE2MjY0NDQ4NjksImV4cCI6MTYyNjUzMTI2OX0.BM2rafazV5_qitmsRILfnR5YkwyJV344kvEImYDzI08

###

DELETE http://localhost:3000/api/sauces/60df2368e8901b65c0eb13c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZWE1MjI5NGM2MzNiZTQ2MzY1YzQiLCJpYXQiOjE2MjUyMzYxMzQsImV4cCI6MTYyNTMyMjUzNH0.mgFJ_6tNMfWKHAkvSv3FmhD93n0vYjquofaJydvcGu4
###

PUT http://localhost:3000/api/sauces/60f205f1e162a2398873a0c4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZWE1MjI5NGM2MzNiZTQ2MzY1YzQiLCJpYXQiOjE2MjY1MjE1MzMsImV4cCI6MTYyNjYwNzkzM30.fiLUXiGADX9nLMzo2_hGsAnQ0W6dIkOeYxSAMrAy2N8
Content-Type: application/json

{
    "userId": "60d5ea52294c633be46365c4",
    "name": "Curry modifié légalement"
}
###
GET http://localhost:3000/api/sauces/60f205f1e162a2398873a0c4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZDAzZDk2M2EwNDQ1MWMyNGFjZDciLCJpYXQiOjE2MjU5NzEzOTYsImV4cCI6MTYyNjA1Nzc5Nn0.zEsNWHBs9VtZ-OXzVbWCKlrOwaaykR1IidaNdWrIXsU

###