GET http://localhost:3000/
###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "100pour100inde@gmail.com",
    "password": "admin"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "100pour100inde@gmail.com",
    "password": "admin"
}
###

GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZDAzZDk2M2EwNDQ1MWMyNGFjZDciLCJpYXQiOjE2MjcwMzc0ODUsImV4cCI6MTYyNzEyMzg4NX0.5Rl3zwJG5komcrXsQBVXsfIu3ROzq6QoMcxi99oykWw

###

DELETE http://localhost:3000/api/sauces/60df2368e8901b65c0eb13c0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZWE1MjI5NGM2MzNiZTQ2MzY1YzQiLCJpYXQiOjE2MjUyMzYxMzQsImV4cCI6MTYyNTMyMjUzNH0.mgFJ_6tNMfWKHAkvSv3FmhD93n0vYjquofaJydvcGu4
###

PUT http://localhost:3000/api/sauces/60ea6473d557b629e4d75127
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZWE1MjI5NGM2MzNiZTQ2MzY1YzQiLCJpYXQiOjE2MjcwNDkzMDQsImV4cCI6MTYyNzEzNTcwNH0.ctAcEOoHqOeV4O8NQ52pz0yttUyJq-7B1jboJM7ibys
Content-Type: application/json

{
    "name": "Curry modifié légalement"
}
###
GET http://localhost:3000/api/sauces/60ea6473d557b629e4d75127
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZDAzZDk2M2EwNDQ1MWMyNGFjZDciLCJpYXQiOjE2MjcwMzc1NzgsImV4cCI6MTYyNzEyMzk3OH0.dEV6ARvWju_CvCNgL_Op3UX02vqtFmAZj9DmOj6KFcw

###

POST http://localhost:3000/api/sauces/60ea6473d557b629e4d75127/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQ1ZDAzZDk2M2EwNDQ1MWMyNGFjZDciLCJpYXQiOjE2MjcwNTc1MDgsImV4cCI6MTYyNzE0MzkwOH0.sWUc1WXj6eCRpDCZlBztCxQ_4hc8yeXWYba3TwJU1cg
Content-Type: application/json

{
    "like": -1,
    "userId": "60d5d03d963a04451c24acd7"
}